#!/usr/bin/env bash
# This script audits subdomains of a given domain and displays their DNS records

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

# Function to display DNS records
display_dns_records() {
    local record_type=$(dig $1.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    echo "The subdomain $1 is a $record_type record and points to $(dig $1.$domain +short)"
}

if [ -z "$subdomain" ]; then
    display_dns_records www
    display_dns_records lb-01
    display_dns_records web-01
    display_dns_records web-02
else
    display_dns_records $subdomain
fi
